### ISSUE TITLE
Add margin of error fields to ACS downloads

### ISSUE THREAD

**Issue by palewire** [datadesk/census-data-downloader#4]

**Comment by iandees** [comment]
It's important to note that MoE data can't be added together in the same way that you add together the estimates. Some more info in this PDF: https://www.census.gov/content/dam/Census/programs-surveys/acs/guidance/training-presentations/20180418_MOE.pdf

**Comment by palewire** [comment]
There are certainly multiple different ways to implement this feature.

My hope is that we can do it "magically" by inferring the companion margin of error field for each value field included in the keys of the `RAW_FIELD_CROSSWALK` on our table configuration classes.

I suspect such a feature could be combined with[ the `get_api_fields` method](https://github.com/datadesk/census-data-downloader/blob/master/census_data_downloader/core/geotypes.py#L54-L59) on the `BaseGeoTypeDownloader` class to append all of the margin fields to each raw data download from the census API. 

Those raw values could then by appended to the processed files with their headers renamed by appending `"_moe"` to the clean names provided by the values in `RAW_FIELD_CROSSWALK`. 

I believe that could be done by expanding [the `raw_field_mapper` section](https://github.com/datadesk/census-data-downloader/blob/master/census_data_downloader/core/geotypes.py#L120-L124) of the `process` method on the same base geotype class.
