### ISSUE TITLE
Clarify that this tool works only for ACS tables in README

### ISSUE THREAD

**Issue by ghing** [datadesk/census-data-downloader#65]
I could be wrong about this, but looking through the source code quickly, it seems like all of the tables are ACS tables. I love this tool, but always forget whether or not it supports other kinds of census data, e.g. [population estimates](https://www.census.gov/data/developers/data-sets/popest-popproj/popest.html). It would be selfishly helpful to have a note in the README that clarifies this.

If I'm wrong about this only covering ACS tables, please let me know.

If my request makes sense to you all, I'm happy to make a pull request for this little documentation change.

**Comment by palewire** [comment]
Yes, that's a good idea. A pull request would be welcome.
